FROM gcc:12.2

ENV DEBIAN_FRONTEND noninteractive

COPY ./install_boost_latest.sh /

RUN apt update -y && \
    apt install -y wget && \
    chmod u+x ./install_boost_latest.sh && \
    ./install_boost_latest.sh
    