# https://hub.docker.com/_/gcc/
FROM gcc:14.2

# https://pypi.org/project/meson/
ARG MESON_VERSION=1.6.1
# https://pypi.org/project/ninja/
ARG NINJA_VERSION=1.11.1.3
# https://pypi.org/project/gcovr/
ARG GCOVR_VERSION=8.2
# https://pypi.org/project/pre-commit/
ARG PRECOMMIT_VERSION=4.0.1

ENV DEBIAN_FRONTEND=noninteractive

# install CMake (for building Boost)
COPY ./cmake_install/get_cmake.sh /
RUN chmod u+x /get_cmake.sh && \
    /get_cmake.sh
ENV PATH="${PATH}:/opt/cmake/bin"

# install CUDA
# https://hub.docker.com/r/nvidia/cuda/tags
COPY --from=nvidia/cuda:12.6.3-devel-ubuntu22.04 /usr/local/cuda-12.6/ /usr/local/cuda-12.6/
COPY --from=nvidia/cuda:12.6.3-devel-ubuntu22.04 /usr/local/cuda-12.6/lib64/ /lib64/

# install Boost (headers and libraries)
COPY --from=boost:14.2 /opt/boost/include/* /usr/include/boost/
COPY --from=boost:14.2 /opt/boost/lib/* /usr/lib/x86_64-linux-gnu/

# install muon
COPY ./muon_install/get_install_muon.sh /
RUN chmod +x /get_install_muon.sh && \
    /get_install_muon.sh

# install, configure ccache
COPY ./ccache_install/get_configure_ccache.sh /
RUN chmod +x /get_configure_ccache.sh && \
    /get_configure_ccache.sh

# build and install mold linker
COPY ./mold_linker_install/get_build_install_mold.sh /
RUN chmod +x /get_build_install_mold.sh && \
    /get_build_install_mold.sh

# Debian backports to get pipx
RUN echo "deb http://deb.debian.org/debian bookworm-backports main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb-src http://deb.debian.org/debian bookworm-backports main contrib non-free" >> /etc/apt/sources.list && \
    apt-get update -y

# general dependencies
RUN apt-get clean && apt-get update -y && \
    apt-get install --no-install-recommends -y bison \
    clang-format \
    clang-tidy \
    cmake \
    curl \
    flex \
    freeglut3-dev \
    git \
    libaspell-dev \
    libglfw3 \
    libglfw3-dev \
    libmpc-dev \
    libpistache-dev \
    mesa-utils \
    pkg-config \
    pipx \
    python3.11-dev \
    texinfo \
    vim \
    wget && \
    curl -fsSL https://deb.nodesource.com/setup_21.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# install GDB (15.1 works with GCC 13.3)
# need libmpc-dev, texinfo, bison, flex
COPY ./gdb_install/get_install_gdb.sh /
RUN chmod +x /get_install_gdb.sh && \
    /get_install_gdb.sh

# pipx configuration for any user
RUN export PIPX_BIN_DIR=/usr/local/bin && \
    mkdir -m 755 -p /usr/local/pipx && \
    export PIPX_HOME=/usr/local/pipx && \
    export PIPX_MAN_DIR=/usr/local/share/man/ && \
    pipx ensurepath && \
    pipx install gcovr=="$GCOVR_VERSION" && \
    pipx install meson=="$MESON_VERSION" && \
    pipx install ninja=="$NINJA_VERSION" && \
    pipx install pre-commit=="$PRECOMMIT_VERSION" && \
    chmod -R 755 /usr/local/bin

# helper build script for various types of build targets
COPY ./build/build.sh /
RUN chmod +x /build.sh && \
    mkdir build && chmod u+x ./build.sh

# the bleeding edge (at the time of this writing) libstdc++ is needed
# run: strings /usr/local/lib64/libstdc++.so.6.0.33 | grep GLIBCXX
# should see "GLIBCXX_3.4.33", which binaries and libraries need when built with gcc14.2
RUN mv /usr/local/lib64/libstdc++.so.6.0.33 /usr/lib/x86_64-linux-gnu/libstdc++.so.6

# set envrionment variables for container (find CMake binary and CUDA libraries)
ENV PATH=${PATH}:/usr/local/cuda-12.6/bin/:/opt/cmake/bin
# for meson install (i.e. ninja -C install debug)
ENV PYTHONPATH=/usr/local/lib/python3/dist-packages

# port in GCC 13.3 for NVCC
ENV NVCC_CCBIN="/usr/local/bin/gcc13.3"

COPY --from=gcc:13.3 /usr/local/include/c++ /usr/local/include/c++
COPY --from=gcc:13.3 /usr/local/libexec/gcc/x86_64-linux-gnu/ /usr/local/libexec/gcc/x86_64-linux-gnu/
COPY --from=gcc:13.3 /usr/local/lib/gcc/x86_64-linux-gnu/ /usr/local/lib/gcc/x86_64-linux-gnu/
COPY --from=gcc:13.3 /usr/local/bin/gcc /usr/local/bin/gcc13.3

ENTRYPOINT ["/build.sh"]
