FROM gcc:13.2

ENV DEBIAN_FRONTEND noninteractive

COPY ./install_boost_latest.sh /

RUN apt-get update -y && \
    apt-get install -y wget && \
    chmod u+x /install_boost_latest.sh && \
    /install_boost_latest.sh
    