FROM gcc:13.2

ENV DEBIAN_FRONTEND noninteractive

# copy over install script
COPY ./install_selene.sh /

# install deps
RUN apt-get clean && apt-get update -y && apt-get install libjpeg62-turbo-dev libpng-dev -y

COPY --from=cmake:latest /opt/cmake /opt/cmake
# update path with cmake binary location
ENV PATH="${PATH}:/opt/cmake/bin" MY_INSTALL_DIR="/usr/local" PATH="$MY_INSTALL_DIR/bin:$PATH"

# installation
RUN chmod +x /install_selene.sh && \
    /install_selene.sh     